import Groq from "groq-sdk";
import "dotenv/config";

const apiKey = process.env.GROQ_API_KEY;

console.log(
    "GROQ API KEY:",
    apiKey ? "✅ Loaded" : "❌ Missing"
);

const groq = new Groq({
    apiKey,
});

const main = async (prompt) => {
    try {
        if (!prompt || !prompt.trim()) {
            throw new Error("Prompt is required");
        }

        console.log("🤖 Groq prompt:", prompt);

        const completion = await groq.chat.completions.create({
            model: "openai/gpt-oss-120b",

            messages: [
                {
                    role: "system",
                    content: `
You are a professional blog content writer and SEO content specialist.

Your task is to generate high-quality, engaging, informative, and professional blog articles.

Follow these rules carefully:

1. Understand the topic provided by the user.
2. Create an attractive and engaging introduction.
3. Explain the topic clearly using simple and professional English.
4. Use meaningful headings and subheadings.
5. Use paragraphs, bullet points, or numbered lists wherever they improve readability.
6. Provide useful and practical information.
7. Keep the content directly related to the given topic.
8. Do not invent statistics, facts, companies, or research.
9. Do not mention AI or say that the content was generated by AI.
10. Do not write phrases such as "Here is your blog".
11. Make the article suitable for publishing directly on a professional website.
12. Use proper grammar and natural language.
13. Make the content engaging rather than repetitive.
14. Include a strong conclusion.
15. The final content should be a complete blog article, not just a short description.

The article should have a professional and human-written tone.
                    `,
                },
                {
                    role: "user",
                    content: `
Write a complete, high-quality blog article about:

${prompt.trim()}
                    `,
                },
            ],

            temperature: 0.7,
            max_tokens: 3000,
        });

        console.log("🤖 Groq API response received");

        const content =
            completion?.choices?.[0]?.message?.content;

        if (!content) {
            throw new Error(
                "Groq returned an empty response"
            );
        }

        return content.trim();

    } catch (error) {
        console.error("❌ GROQ ERROR");
        console.error("Message:", error.message);
        console.error("Status:", error.status);
        console.error("Code:", error.code);

        throw error;
    }
};

export default main;
